### PR TITLE
Merge brand new extended 'About' section and new 'Overview' (about direct) sections

### PR DESCRIPTION
**Pull request by dev-alto**
any reviewers, feel free to give input and ideas for the added sections. thanks. other than that, just review the website's visuals 👀.

afterwards planning to (finally) review and merge #9, and clean up the structuring of our website to better prepare and support future development.

### CODE REVIEW

**Comment by dev-alto** [comment]
#### 📝 Changed routes:


| [**/hackathon/\[...slug\]**](https://the-skycsc-website-oavzqren0-skylinecsclub.vercel.app/hackathon/[...slug]) | [**/hackathon**](https://the-skycsc-website-oavzqren0-skylinecsclub.vercel.app/hackathon) |
|:-:|:-:|
|<a href="https://the-skycsc-website-oavzqren0-skylinecsclub.vercel.app/hackathon/[...slug]">Screenshot of /hackathon/[...slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/02n2dAfgQxhkedfFwusSy_yEZtZCRjjrI4KGkho8NswrkyJV17LdMmZiOH3feFMqHgMAKM1jBSYm0FQDtR6PzA.png">(view full size)</a> |<a href="https://the-skycsc-website-oavzqren0-skylinecsclub.vercel.app/hackathon">Screenshot of /hackathon</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/iVjhJUdwdbWVxyeNJUjGusJyrCCeIw4erQL-ykJYObH2vbghzmeo4BRiel8aKMe0zjXKwJAzwH73tOYXS9qeNQ.png">(view full size)</a> |



| [**/**](https://the-skycsc-website-oavzqren0-skylinecsclub.vercel.app/) |
|:-:|
|<a href="https://the-skycsc-website-oavzqren0-skylinecsclub.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/fF1Kw3xf94bLGcX32fSf3FJXZ2HMmK0fOGzrrokgBLQ7zAWnTSkUdtlcv8F71iJHKoOUP-w7yZAtGRNxLmN6Ww.png">(view full size)</a> |







Commit 314537ef13c32eb33d09cd5e717589581d41f7eb (https://the-skycsc-website-oavzqren0-skylinecsclub.vercel.app).

**Comment by johncmanuel** [comment]
@dev-alto The preview URLs from Vercel require access. Is there a way to make them publicly accessible?

image

**Comment by dev-alto** [comment]
Right, you can try this shared preview link: https://the-skycsc-website-git-aboutextended-skylinecsclub.vercel.app?_vercel_share=esk35yCA27sPXflSAB8x16EJ3HGCKMFf

**Comment by johncmanuel** [comment]
Is the social media links box supposed to overlap a bit with a person's portrait when hovering (see Tyler's social media links blocking a bit of Jayan's portrait)? It's fine if so, I was just curious. 

image

Off-topic question tho: what's route `/hackathon/[...slug]` about? Seems like a personalized hackathon page for a user? This looks cool!     

Otherwise, this is so :fire: especially the Discord section near the footer in the homepage!

**Review by johncmanuel — APPROVED** [review]
LGTM

**Comment by matthewaol** [comment]
Screenshot from 2024-07-10 20-56-25

image

Some txt overlap :crying_cat_face: 

Regarding the photos I would've preferred a toggle to zoom in the pictures instead of needing to hold down the click (I'm on trackpad)  

SO DOPE Man

**Comment by dev-alto** [comment]
Heyo @matthewaol & @johncmanuel, thanks for coming through! Really appreciate your guys' feedback. 

Toggle-to-zoom for the Gallery is a good point for UX; was told this is already replicated on mobile luckily but I did not account for trackpad usage! Nice catch.

Regarding the cases of text overflow/visual artifacts—interesting, seems that there may be some cross-browser CSS styling/compatibility issues to be fixed? Not quite sure yet. Officer card overlapping is intended, ~see below.

I currently run Vivaldi(chromium) on Windows 11, attached is what those sections are ideally meant to look referencing off my browser. Same results on my Samsung phone running Chrome. Let me know what you guys run.

<video src='https://github.com/Skyline-College-Computer-Science-Club/project.ClubWebsite/assets/51037255/b42eb605-d121-4ec4-8632-f485334ab53f'></video>
<video src='https://github.com/Skyline-College-Computer-Science-Club/project.ClubWebsite/assets/51037255/2d062ae5-21ba-480e-89ac-6e92e3f79cd1'></video>

**Comment by johncmanuel** [comment]
> Regarding the cases of text overflow/visual artifacts—interesting, seems that there may be some cross-browser CSS styling/compatibility issues to be fixed? Not quite sure yet. Officer card overlapping is intended, ~see below.

@dev-alto It's actually one of my extensions, Dark Reader, that caused the CSS to be funky! After turning it off, it reflects what you've recorded above. Sorry about that!

**Comment by dev-alto** [comment]
> /hackathon/[...slug]

Thanks for noticing—that's exactly what it's for. Intended for usage on mobile that QR scanned-in people participating in our hackathon, simply uses URL params as seen being a dynamic slug route. The confirm button queries to a database just based off these params. Scanned QR codes and their URL param links are sourced in the form of tickets that were sent over email to our hackathon contestants.

The implementation leaves a lot to be desired, it was made over a short afternoon and was only used internally.

If you guys want to demo it, you can access this via mobile: https://skycsc.vercel.app/hackathon/_/

and try scanning this QR code using the site's built-in scanner at the bottom (it might use the wrong camera).
image

https://skycsc.vercel.app/hackathon/devalto/devalto%40my.smccd.edu/🌄%20Skyline%20College

**Pull request merged**
